{
    "name": "PBMS Registry Addon",
    "version": "1.0",
    "summary": "OpenG2P Registry Addon",
    "description": "OpenG2P Registry Addon",
    "category": "OpenG2P",
    "license": "LGPL-3",
    "depends": ["base_setup", "web", "g2p_pbms"],
    "data": [
        "security/ir.model.access.csv",
        "views/eligibility/eligibility_rule_view.xml",
        "views/entitlement/entitlement_rule_view.xml",
        "views/priority/priority_rule_view.xml",
        "views/registry/elec_monthly_avg_registry_view.xml",
        "views/registry/govt_employees_registry_view.xml",
        "views/registry/land_holdings_registry_view.xml",
        "views/registry/lrs_brs_application_registry_view.xml",
        "views/registry/professional_tax_payers_registry_view.xml",
        "views/registry/ration_card_applicants_registry_view.xml",
        "views/registry/registry_families_registry_view.xml",
        "views/registry/registry_individuals_registry_view.xml",
        "views/registry/residential_houses_registry_view.xml",
        "views/registry/vehicle_ownership_registry_view.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "/g2p_registry_addon/static/src/css/registry_styles.scss",
            "/g2p_registry_addon/static/src/js/beneficiaries_widget.js",
            "/g2p_registry_addon/static/src/xml/g2p_beneficiaries_info_tpl.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
